# This file was generated by GoReleaser. DO NOT EDIT.
cask "mls" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "d844c164f51a2283718d5566d1c471a63cba40aac5ee05ae67d84c74b34796c1"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a11fa17b5eacda246cb1d9787eec6cd5a070c520e264b9a94070059878910910"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e3ee4459a1df460482c8ee5f9e1c7f4937a957f83dbfca1a3dbaf2bc9ea877e"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b9484ee6fb8cdf249877eda6146ded4e23a3eb344ceae80691dbf8878acb022"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mls"
  desc "High-performance storage cleanup tool"
  homepage "https://github.com/MohamedLamineAllal/MrLeanStorage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mls"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mls"]
    end
  end

  # No zap stanza required

end
