# This file was generated by GoReleaser. DO NOT EDIT.
cask "mls" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "e3916e6af4bf84c5b37142dc852d2a8840f69416b76b166adcfcaa7b298d5df2"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b25f942b0eb7d42de812378d95e0db82890267fcea454c759724517bfdb238e6"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c228bcfede7b96e1642b3c4242ef8a67f50dfbdc06b9e2175ecbb0197a682362"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a5c27fac78ecce2f39ebd12733eea6d036effb23519185772a1ce9fd77b2cb9"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mls"
  desc "High-performance storage cleanup tool"
  homepage "https://github.com/MohamedLamineAllal/MrLeanStorage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mls"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mls"]
    end
  end

  # No zap stanza required

end
