# This file was generated by GoReleaser. DO NOT EDIT.
cask "mls" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "b3c7ec88be4af983d670ca3c8156cf7f50518f4ebf083777e20f6d47aa33ac26"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6838aaaced5e3092f5e7d54b007a9a83704559fee0572ef1251dacd8ee1d0ee3"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d27f6020d541dc03bbd40ec4999c4fb667e1d03072ace38f33c9e7347ac67fd0"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d694734971fcf62ccf662c711f4364e8946dbe2c5a369beab9b5118353441a7c"
      url "https://github.com/MohamedLamineAllal/MrLeanStorage/releases/download/v#{version}/mls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mls"
  desc "High-performance storage cleanup tool"
  homepage "https://github.com/MohamedLamineAllal/MrLeanStorage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mls"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mls"]
    end
  end

  # No zap stanza required

end
